Import("cli_env")

detinfo_objects =[cli_env.Object("detinfo.cpp")]
detinfo_objects.extend(SConscript("../common/SConscript"))
detinfo = cli_env.Program(target="detinfo",source=detinfo_objects)
detinfo_install = cli_env.Install("$PREFIX/bin",detinfo)

cli_env.Alias("all",[detinfo])
cli_env.Alias("install",[detinfo_install])
