Import("cli_env")

nxcat_objects =[cli_env.Object(["main.cpp"])]
nxcat_objects.extend(SConscript("../common/SConscript"))
nxcat = cli_env.Program(target="nxcat",source=nxcat_objects)
nxcat_install = cli_env.Install("$PREFIX/bin",nxcat)

cli_env.Alias("all",[nxcat])
cli_env.Alias("install",[nxcat_install])
