import os.path as path
Import("build_env")

#--------------------building objects-------------------------------------------
sources = ["main.cpp","ProgramConfig.cpp","Operation.cpp",
           "OperationDispatcher.cpp","Exceptions.cpp","ROIRange.cpp","ROI.cpp"]
objects = build_env.Object(sources)

#----------------------linking binary------------------------------------------
detops = build_env.Program("detops",objects)

#----------------------installation--------------------------------------------
detops_inst = build_env.Install("${BININSTPATH}",[detops])

build_env.Alias("all",[detops])
build_env.Alias("install",[detops_inst])