from os import path

Import("cli_env")
prg_env = cli_env.Clone()

src_list = ["main.cpp","det2nx_utils.cpp"]
src_list.extend(SConscript(["../common/SConscript"]))
det2nx = cli_env.Program("det2nx",src_list)

det2nx_inst = cli_env.Install("$PREFIX/bin",[det2nx])

cli_env.Alias("all",[det2nx])
cli_env.Alias("install",[det2nx_inst])
