Import("cli_env")

nxsh_objects =[cli_env.Object(["main.cpp","interpreter.cpp","environment.cpp"])]
nxsh_objects.extend(['cmd_mkfile.cpp','cmd_ls.cpp','cmd_open.cpp','cmd_cd.cpp'])
nxsh_objects.extend(["cmd_mkgrp.cpp","cmd_mkfield.cpp","cmd_mkattr.cpp","cmd_cat.cpp"])
nxsh_objects.extend(SConscript("../common/SConscript"))
nxsh = cli_env.Program(target="nxsh",source=nxsh_objects)
nxsh_install = cli_env.Install("$PREFIX/bin",nxsh)

cli_env.Alias("all",[nxsh])
cli_env.Alias("install",[nxsh_install])
