######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 15:51:08 2012
######################################################################
# Input
HEADERS += MainWidget.hpp
SOURCES += main.cpp MainWidget.cpp
