Import("program_env")

xml2nx_objects =[program_env.Object("main.cpp")]
xml2nx_objects.extend(SConscript("../common/SConscript"))
xml2nx = program_env.Program(target="xml2nx",source=xml2nx_objects)
xml2nx_install = program_env.Install("$PREFIX/bin",xml2nx)

program_env.Alias("all",[xml2nx])
program_env.Alias("install",[xml2nx_install])
