Import("cli_env")

mcaops_src = ["mcaops.cpp","scale_operation.cpp","io.cpp",
              "rebin_operation.cpp","operation.cpp",
              "mcaops_utils.cpp"]

if GetOption("static"):
    mcaops = cli_env.Program("mcaops",mcaops_src,LINKFLAGS="--static")
else:
    mcaops = cli_env.Program("mcaops",mcaops_src)

cli_env.Alias("all",mcaops)
mcaops_inst = cli_env.Install("$PREFIX/bin",mcaops)
cli_env.Alias("install",mcaops_inst)
    
