Import("program_env")

mcaops_src = ["main.cpp"]

if GetOption("static"):
    mcaops = program_env.Program("mcaops",mcaops_src,LINKFLAGS="--static")
else:
    mcaops = program_env.Program("mcaops",mcaops_src)
    
